#!/bin/sh

# https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-applications-using-uwsgi-web-server-with-nginx
# http://uwsgi-docs.readthedocs.org/en/latest/StaticFiles.html
# http://uwsgi-docs.readthedocs.org/en/latest/Upstart.html

uwsgi --static-map /static=./static --static-map /media=./media --socket :$1 --protocol=http -w wsgi --master --processes 2
